project:
  seed: 42
  experiment_name: "house-price-regression"
  artifact_dir: "artifacts"
  target: "SalePrice"

data:
  train_path: "train.csv"
  test_path: "test.csv"

model:
  type: "random_forest"   # (bisa ganti: random_forest/xgboost)
  params:
    n_estimators: 300
    max_depth: 10
    random_state: 42
    n_jobs: -1

train:
  test_size: 0.2
  shuffle: true
  scoring: "rmse"         # hanya penamaan; metrik dihitung manual
